name: cufp-api

dependencies:
    - base
    - servant
    - servant-docs
    - either
    - transformers
    - http-media
    - bytestring
    - aeson
    - servant-server
    - servant-client
    - wai
    - warp

library:
  source-dirs:
    - src
  exposed-modules:
    - ChatApi
    - Lambda.Api
