name: cufp-api

dependencies:
    - aeson
    - base
    - bytestring
    - either
    - http-media
    - logging-facade
    - servant
    - servant-client
    - servant-docs
    - servant-server
    - string-conversions
    - text
    - transformers
    - wai
    - wai-extra
    - warp

library:
  source-dirs:
    - src
  exposed-modules:
    - ChatApi
    - Lambda.Api
