library:
  dependencies:
    - base
    - either
    - bytestring
    - servant
    - servant-client
    - servant-docs
    - servant-server
    - JuicyPixels
    - http-media
    - wai
    - warp
    - servant-JuicyPixels
    - transformers
    - warp
