version: "0.1"

dependencies:
  - base
  - cufp-api
  - servant
  - servant-client
  - either

library:
  source-dirs:
    - src

executables:
  ip-client:
    main: Main.hs
    source-dirs:
      - driver
      - src
    dependencies:
      - getopt-generics
