version: "0.1"

ghc-options: -Wall

dependencies:
  - base
  - cufp-api
  - wai
  - servant-server

executables:
  node-template:
    main: Main.hs
    source-dirs:
      - driver
      - src
    dependencies:
      - warp
      - logging-facade

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - hspec-wai
      - hspec-wai-json
      - wai-extra
