name: ip-manager

ghc-options: -Wall

dependencies:
  - base
  - servant-server
  - split
  - aeson
  - string-conversions
  - transformers
  - either
  - wai

executables:
  ip-manager:
    main: ip-manager.hs
    source-dirs:
      - driver
      - src
    dependencies:
      - warp
      - logging-facade

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - hspec-wai
      - hspec-wai-json
      - wai-extra
